/* Generated by BuildNumber Version 0.8 */

#ifndef BUILD_NUMBER_H_ 
#define BUILD_NUMBER_H_ 

#define BUILDNUMBER 372
#define _VERSION_MAJOR 2
#define _VERSION_MINOR 94
#define _VERSION_MAINTENANCE "-dev"
#define _VERSION_FULL "2.94.372-dev"
#endif /* BUILD_NUMBER_H_ */
