/* Generated by BuildNumber Version 0.8 */

#ifndef BUILD_NUMBER_H_ 
#define BUILD_NUMBER_H_ 

#define BUILDNUMBER 349
#define _VERSION_MAJOR 2
#define _VERSION_MINOR 93
#define _VERSION_MAINTENANCE "-dev"
#define _VERSION_FULL "2.93.349-dev"
#endif /* BUILD_NUMBER_H_ */
