/* Generated by BuildNumber Version 0.8 */

#ifndef BUILD_NUMBER_H_ 
#define BUILD_NUMBER_H_ 

#define BUILDNUMBER 3
#define _VERSION_MAJOR 2
#define _VERSION_MINOR 97
#define _VERSION_MAINTENANCE "-demo"
#define _VERSION_FULL "2.97.3-demo"
#endif /* BUILD_NUMBER_H_ */
