/* Generated by BuildNumber Version 0.8 */

#ifndef BUILD_NUMBER_H_ 
#define BUILD_NUMBER_H_ 

#define BUILDNUMBER 24
#define _VERSION_MAJOR 3
#define _VERSION_MINOR 2
#define _VERSION_MAINTENANCE ""
#define _VERSION_FULL "3.2.24"
#endif /* BUILD_NUMBER_H_ */
