PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS wallet;

DROP TABLE IF EXISTS inventory;

DROP TABLE IF EXISTS inventoryLimit;

----------------------------------
--- Rpg
----------------------------------

CREATE TABLE rpgCharacter(
	id INTEGER NOT NULL PRIMARY KEY,
	username TEXT NOT NULL REFERENCES user(username) ON UPDATE CASCADE ON DELETE CASCADE,
	character TEXT NOT NULL,
	level INTEGER NOT NULL DEFAULT 1,
	coin INTEGER,
	UNIQUE (username, character)
);

CREATE TABLE rpgTarget(
	username TEXT NOT NULL REFERENCES user(username) ON UPDATE CASCADE ON DELETE CASCADE,
	character TEXT NOT NULL,
	coin INTEGER,
	UNIQUE (username)
);

CREATE TABLE rpgWeekly(
	character TEXT NOT NULL,
	timestamp TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rpgUserWeekly(
	id INTEGER NOT NULL PRIMARY KEY,
	username TEXT NOT NULL REFERENCES user(username) ON UPDATE CASCADE ON DELETE CASCADE,
	character TEXT NOT NULL REFERENCES rpgWeekly(character) ON UPDATE CASCADE ON DELETE CASCADE,
	coin INTEGER
);

CREATE TABLE rpgGame(
	id INTEGER NOT NULL PRIMARY KEY,
	gameid INTEGER REFERENCES game(id) ON UPDATE CASCADE ON DELETE SET NULL,
	terrain TEXT,
	character TEXT,
	coinCharacter INTEGER,
	coinTarget INTEGER
);

CREATE TABLE rpgDrop(
	id INTEGER NOT NULL PRIMARY KEY,
	type INTEGER NOT NULL DEFAULT 0,
	tier INTEGER NOT NULL DEFAULT 0,
	username TEXT NOT NULL REFERENCES user(username) ON UPDATE CASCADE ON DELETE CASCADE,
	gameid INTEGER REFERENCES rpgGame(id) ON UPDATE CASCADE ON DELETE SET NULL,
	timestamp TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
	terrain TEXT,
	finished BOOL NOT NULL DEFAULT FALSE,
	xp INTEGER,
	coinCharacter INTEGER,
	coinTarget INTEGER
);

