PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS game(
	id INTEGER PRIMARY KEY,
	type INTEGER NOT NULL DEFAULT 0 CHECK (type>=-1 and type<=1),
	chNum INTEGER NOT NULL DEFAULT 0,
	chRand INTEGER,
	introId INTEGER REFERENCES intro(id) ON UPDATE CASCADE ON DELETE CASCADE,
	objectiveId INTEGER REFERENCES objective(id) ON UPDATE CASCADE ON DELETE CASCADE,
	done BOOL NOT NULL DEFAULT false
);
