// Auto generated
Q_IMPORT_PLUGIN(ModuleTruefalse)
Q_IMPORT_PLUGIN(ModuleCalculator)
Q_IMPORT_PLUGIN(ModulePlusminus)
Q_IMPORT_PLUGIN(ModuleSimplechoice)
Q_IMPORT_PLUGIN(ModuleMultichoice)
Q_IMPORT_PLUGIN(ModulePair)
Q_IMPORT_PLUGIN(ModuleFillout)
Q_IMPORT_PLUGIN(ModuleBinding)
Q_IMPORT_PLUGIN(ModuleNumbers)
Q_IMPORT_PLUGIN(ModuleSequence)
Q_IMPORT_PLUGIN(ModuleOrder)
Q_IMPORT_PLUGIN(ModuleImages)
Q_IMPORT_PLUGIN(ModuleWriter)
Q_IMPORT_PLUGIN(ModuleText)
Q_IMPORT_PLUGIN(ModuleBlock)
